[log]
# valid levels are "debug", "info", "warn", "error"
level = "info"
# valid formats are "text", "json", "custom"
format = "custom"
# whether to add the log source to the log message
add_source = true

[bot]
# add guild ids the commands should sync to, leave empty to sync globally
dev_guilds = []
